export const QUIZ = [
  {
    name: 'investment_experience',
    question: 'Select your investment experience level:',
    options: ['Novice', 'Intermediate', 'Experienced'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'risk_tolerance',
    question: 'Rate your comfort with investment risk:',
    options: ['Very conservative', 'Conservative', 'Moderate', 'Aggressive'],
    type: 'choice',
    scores: [1, 2, 3, 4],
  },
  {
    name: 'investment_goals',
    question: 'What are your primary investment objectives?',
    options: ['Preserve capital', 'Generate income', 'Grow wealth', 'Speculate'],
    type: 'choice',
    scores: [1, 2, 3, 4],
  },
  {
    name: 'investment_time_horizon',
    question: 'Choose your investment time horizon:',
    options: ['Short-term (less than 1 year)', 'Medium-term (1-5 years)', 'Long-term (more than 5 years)'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'financial_knowledge',
    question: 'Rate your familiarity with financial markets:',
    options: ['Limited', 'Moderate', 'Extensive'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'liquidity_preference',
    question: 'How important is liquidity for your investments?',
    options: ['Very important', 'Moderately important', 'Less important'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'investment_style',
    question: 'Which investment style suits you best?',
    options: ['Conservative', 'Moderate', 'Aggressive'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'primary_income_source',
    question: 'What is your primary source of income?',
    options: ['Employment', 'Business/Entrepreneurship', 'Investments', 'Other'],
    type: 'choice',
    scores: [1, 2, 3, 4],
  },
  {
    name: 'investment_confidence',
    question: 'How confident are you in making investment decisions?',
    options: ['Not confident', 'Moderately confident', 'Very confident'],
    type: 'choice',
    scores: [1, 2, 3],
  },
  {
    name: 'investment_history',
    question: 'Have you previously invested in financial markets?',
    options: ['Yes', 'No'],
    type: 'choice',
    scores: [1, 2],
  },
];
